[theme]
primaryColor = "#4A90E2"
backgroundColor = "#242831"
secondaryBackgroundColor = "#323640"
textColor = "#E0E0E0"
font = "sans serif"

[server]
fileWatcherType = "poll"
folderWatchBlacklist = ["venv", ".git", ".streamlit", "data", "node_modules"]
